version: "3.1"

services:
  db:
    image: postgres
    restart: always
    logging:
      driver: none
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  scheduler:
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    logging:
      driver: none
    command: [ "dask-scheduler" ]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: dask-worker
    logging:
      driver: none
    volumes:
      - task_2_data:/task_2_data
    command: [ "dask-worker", "tcp://scheduler:8786" ]

  task_2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DASK_SCHEDULER_ADDRESS=tcp://scheduler:8786
      - TASK_1_DATA_DIR=/task_1_data
      - TASK_2_DATA_DIR=/task_2_data
      - DB_HOST=db
    volumes:
      - task_1_data:/task_1_data
      - task_2_data:/task_2_data
      - ./code:/code
    ports:
      - "8888:8888"
    entrypoint: [ "jupyter", "notebook", "--allow-root", "--ip",  "0.0.0.0", "--notebook-dir", "/code/notebooks" ]

volumes:
  task_1_data:
  task_2_data:
